In [1]:
import pandas as pd
df = pd.read_csv('weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [2]:
df.Gender = df['Gender'].replace(['Male', 'Female'], [0,1])
df.head()

Gender     Height      Weight
0       0  73.847017  241.893563
1       0  68.781904  162.310473
2       0  74.110105  212.740856
3       0  71.730978  220.042470
4       0  69.881796  206.349801

In [3]:
df.tail()

Gender     Height      Weight
8550       1  60.483946  110.565497
8551       1  63.423372  129.921671
8552       1  65.584057  155.942671
8553       1  67.429971  151.678405
8554       1  60.921791  131.253738

In [4]:
x = df.drop('Weight', axis=1)

In [5]:
x.head()

Gender     Height
0       0  73.847017
1       0  68.781904
2       0  74.110105
3       0  71.730978
4       0  69.881796

In [7]:
y = df['Weight']
y.head()

0    241.893563
1    162.310473
2    212.740856
3    220.042470
4    206.349801
Name: Weight, dtype: float64

In [8]:
import numpy as np 
from matplotlib import pyplot as plt 

In [10]:
df.describe()

Gender       Height       Weight
count  8555.000000  8555.000000  8555.000000
mean      0.415546    66.809925   165.632735
std       0.492845     3.851454    32.043922
min       0.000000    54.616858    65.780000
25%       0.000000    63.957684   139.876803
50%       0.000000    66.985923   168.521567
75%       1.000000    69.604427   190.666305
max       1.000000    80.450000   269.989698

# Data Split

In [11]:
from sklearn.model_selection import train_test_split
train, test=train_test_split(df, test_size=.30)

In [12]:
train.head()

Gender     Height      Weight
3854       0  71.017948  203.860914
7133       1  65.728580  137.839896
1191       0  70.064688  192.045218
8006       1  59.917631  118.463414
2717       0  73.696859  232.718678

# Seperate train and test for xtrain, xtest, ytrain, ytest

In [13]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=.30, random_state=42)

In [14]:
xtrain.head()

Gender     Height
553        0  67.594031
1397       0  71.601697
7934       1  62.625985
8367       1  66.136131
3320       0  71.843308

In [15]:
ytrain.head()

553     186.751417
1397    211.031652
7934    143.768451
8367    151.814648
3320    196.505814
Name: Weight, dtype: float64

# LR

In [16]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [17]:
reg.fit(xtrain, ytrain)

LinearRegression()

In [18]:
reg.coef_

array([-19.54151693,   5.9562333 ])

In [19]:
reg.intercept_

-224.25154348584044

In [20]:
reg.predict([[0,67]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([174.81608765])

In [22]:
reg.predict(xtest)

array([142.44868114, 186.0517281 , 198.42283706, ..., 102.94080643,
       190.83713617, 143.34786753])

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [26]:
y_train_pred = reg.predict(xtrain)
y_test_pred = reg.predict(xtest)

In [28]:
mse_train = mean_squared_error(ytrain, y_train_pred)
r2_train = r2_score(ytrain, y_train_pred)
mse_test = mean_squared_error(ytest, y_test_pred)
r2_test = r2_score(ytest, y_test_pred)

In [29]:
mse_train

105.23806184862872

In [30]:
r2_train

0.8973793060969246

In [31]:
mse_test

96.83734437830606

In [32]:
r2_test

0.905911242442266

# KNN

In [56]:
 from sklearn.neighbors import KNeighborsClassifier
m = KNeighborsClassifier(n_neighbors=2)

In [59]:
 m.fit(xtrain, ytrain)

ValueError: Unknown label type: 'continuous'

# The error message "Unknown label type: 'continuous'" typically occurs in scikit-learn, trying to use a classification algorithm, like k-nearest neighbors (KNN), with continuous (numeric) target values, which is not supported by default.

# Second Part of Assignment

In [60]:
df.head()

Gender     Height      Weight
0       0  73.847017  241.893563
1       0  68.781904  162.310473
2       0  74.110105  212.740856
3       0  71.730978  220.042470
4       0  69.881796  206.349801

In [61]:
df.Gender = df['Gender'].replace(['Male', 'Female'], [0,1])
df.head()

Gender     Height      Weight
0       0  73.847017  241.893563
1       0  68.781904  162.310473
2       0  74.110105  212.740856
3       0  71.730978  220.042470
4       0  69.881796  206.349801

In [62]:
df.tail()

Gender     Height      Weight
8550       1  60.483946  110.565497
8551       1  63.423372  129.921671
8552       1  65.584057  155.942671
8553       1  67.429971  151.678405
8554       1  60.921791  131.253738

In [63]:
x = df.drop('Gender', axis=1)

In [64]:
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [65]:
y = df['Gender']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Gender, dtype: int64

In [66]:
df.describe()

Gender       Height       Weight
count  8555.000000  8555.000000  8555.000000
mean      0.415546    66.809925   165.632735
std       0.492845     3.851454    32.043922
min       0.000000    54.616858    65.780000
25%       0.000000    63.957684   139.876803
50%       0.000000    66.985923   168.521567
75%       1.000000    69.604427   190.666305
max       1.000000    80.450000   269.989698

# Data Split

In [67]:
from sklearn.model_selection import train_test_split
train, test=train_test_split(df, test_size=.30)

In [68]:
train.head()

Gender     Height      Weight
1472       0  67.846160  168.067015
7207       1  63.768212  143.723794
4351       0  73.143336  205.721864
2435       0  71.539299  207.307917
171        0  72.213963  205.389761

# Seperate train and test for xtrain, xtest, ytrain, ytest

In [69]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=.30, random_state=42)

In [70]:
xtrain.head()

Height      Weight
553   67.594031  186.751417
1397  71.601697  211.031652
7934  62.625985  143.768451
8367  66.136131  151.814648
3320  71.843308  196.505814

In [71]:
ytrain.head()

553     0
1397    0
7934    1
8367    1
3320    0
Name: Gender, dtype: int64

# KNN for Classification

In [73]:
 from sklearn.neighbors import KNeighborsClassifier
 m = KNeighborsClassifier(n_neighbors=3)

In [74]:
 m.fit(xtrain, ytrain)

KNeighborsClassifier(n_neighbors=3)

In [75]:
m.predict(xtest)

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [76]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [78]:
y_train_pred = m.predict(xtrain)
y_test_pred = m.predict(xtest)

In [79]:
y_train_pred

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [80]:
y_test_pred

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [81]:
mse_train = mean_squared_error(ytrain, y_train_pred)
r2_train = r2_score(ytrain, y_train_pred)
mse_test = mean_squared_error(ytest, y_test_pred)
r2_test = r2_score(ytest, y_test_pred)

In [82]:
mse_train

0.0632932531730127

In [83]:
r2_train

0.7394133501496323

In [84]:
mse_test

0.09855862874951304

In [85]:
r2_test

0.5941098679679464